[build-system]
requires = ["setuptools",]
build-backend = "setuptools.build_meta"

[project]
name = "Agents"
version = "0.0.1"
description = "No Code Agent Builder Microservice"
readme = "README.md"
requires-python = ">=3.13,<3.14" #pyarrow doesn't have 3.14 support
keywords = []
authors = []

dependencies = [
    "black",
    "flake8",
    "pytest",
    "pytest-asyncio",
    "pytest-xdist",
    "pytest-cov",
    "pytest-mock",
    "pytest-timeout",
    "isort",
    "langchain",
    "langchain_openai",
    "langchain_anthropic",
    "python-dotenv",
    "aiolimiter",
    "langgraph>=1.0.2",
    "ipython>=9.7.0",
]

[project.optional-dependencies]
gpu_specifics = [
    "vllm"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
